// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::client::*;
use jup_ag_api_generated::apis::{
    lend_api,
    lend_borrow_api,
    portfolio_api,
    prediction_api,
    price_v2_api,
    price_v3_api,
    recurring_api,
    send_api,
    studio_api,
    swap_v1_api,
    swap_v2_api,
    tokens_v1_api,
    tokens_v2_api,
    tokens_v2_verification_api,
    transaction_api,
    trigger_v1_api,
    trigger_v2_api,
    ultra_api,
};
use jup_ag_api_generated::apis::Error;
use jup_ag_api_generated::models;

impl Lend {
    /// Request for the instruction of an earn deposit transaction to deposit assets 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_deposit_instructions_post(&self, lend_earn_amount_request_body: models::LendEarnAmountRequestBody) -> Result<models::LendInstructionResponse, Error<lend_api::LendV1EarnDepositInstructionsPostError>> {
        lend_api::lend_v1_earn_deposit_instructions_post(&self.config, lend_earn_amount_request_body).await
    }

    /// Request for a base64-encoded unsigned earn deposit transaction to deposit assets 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_deposit_post(&self, lend_earn_amount_request_body: models::LendEarnAmountRequestBody) -> Result<models::LendTransactionResponse, Error<lend_api::LendV1EarnDepositPostError>> {
        lend_api::lend_v1_earn_deposit_post(&self.config, lend_earn_amount_request_body).await
    }

    /// Request for the earnings of one or multiple positions of a user 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_earnings_get(&self, user: &str, positions: &str) -> Result<models::LendUserEarningsResponse, Error<lend_api::LendV1EarnEarningsGetError>> {
        lend_api::lend_v1_earn_earnings_get(&self.config, user, positions).await
    }

    /// Request for the instruction of an earn mint transaction to mint shares 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_mint_instructions_post(&self, lend_earn_shares_request_body: models::LendEarnSharesRequestBody) -> Result<models::LendInstructionResponse, Error<lend_api::LendV1EarnMintInstructionsPostError>> {
        lend_api::lend_v1_earn_mint_instructions_post(&self.config, lend_earn_shares_request_body).await
    }

    /// Request for a base64-encoded unsigned earn mint transaction to mint shares 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_mint_post(&self, lend_earn_shares_request_body: models::LendEarnSharesRequestBody) -> Result<models::LendTransactionResponse, Error<lend_api::LendV1EarnMintPostError>> {
        lend_api::lend_v1_earn_mint_post(&self.config, lend_earn_shares_request_body).await
    }

    /// Request for the position data of one or multiple users 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_positions_get(&self, users: &str) -> Result<Vec<models::LendUserPosition>, Error<lend_api::LendV1EarnPositionsGetError>> {
        lend_api::lend_v1_earn_positions_get(&self.config, users).await
    }

    /// Request for the instruction of an earn redeem transaction to redeem shares 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_redeem_instructions_post(&self, lend_earn_shares_request_body: models::LendEarnSharesRequestBody) -> Result<models::LendInstructionResponse, Error<lend_api::LendV1EarnRedeemInstructionsPostError>> {
        lend_api::lend_v1_earn_redeem_instructions_post(&self.config, lend_earn_shares_request_body).await
    }

    /// Request for a base64-encoded unsigned earn redeem transaction to redeem shares 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_redeem_post(&self, lend_earn_shares_request_body: models::LendEarnSharesRequestBody) -> Result<models::LendTransactionResponse, Error<lend_api::LendV1EarnRedeemPostError>> {
        lend_api::lend_v1_earn_redeem_post(&self.config, lend_earn_shares_request_body).await
    }

    /// Request for the tokens available to be deposited and their information 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_tokens_get(&self) -> Result<Vec<models::LendTokenInfo>, Error<lend_api::LendV1EarnTokensGetError>> {
        lend_api::lend_v1_earn_tokens_get(&self.config).await
    }

    /// Request for the instruction of an earn withdraw transaction to withdraw assets 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_withdraw_instructions_post(&self, lend_earn_amount_request_body: models::LendEarnAmountRequestBody) -> Result<models::LendInstructionResponse, Error<lend_api::LendV1EarnWithdrawInstructionsPostError>> {
        lend_api::lend_v1_earn_withdraw_instructions_post(&self.config, lend_earn_amount_request_body).await
    }

    /// Request for a base64-encoded unsigned earn withdraw transaction to withdraw assets 
    #[allow(clippy::too_many_arguments)]
    pub async fn lend_v1_earn_withdraw_post(&self, lend_earn_amount_request_body: models::LendEarnAmountRequestBody) -> Result<models::LendTransactionResponse, Error<lend_api::LendV1EarnWithdrawPostError>> {
        lend_api::lend_v1_earn_withdraw_post(&self.config, lend_earn_amount_request_body).await
    }
}

impl LendBorrow {
    /// Returns Solana instructions and lookup table addresses for a borrow operate action.
    #[allow(clippy::too_many_arguments)]
    pub async fn build_borrow_operate_instructions(&self, lend_borrow_operate_payload: models::LendBorrowOperatePayload, market: Option<models::LendBorrowMarket>) -> Result<models::LendBorrowOperateInstructionsResponse, Error<lend_borrow_api::BuildBorrowOperateInstructionsError>> {
        lend_borrow_api::build_borrow_operate_instructions(&self.config, lend_borrow_operate_payload, market).await
    }

    /// Builds a base64-encoded unsigned versioned transaction for a borrow operate action.  Positive `colAmount` / `debtAmount` values deposit collateral or borrow debt. Negative values withdraw collateral or pay back debt. 
    #[allow(clippy::too_many_arguments)]
    pub async fn build_borrow_operate_transaction(&self, lend_borrow_operate_payload: models::LendBorrowOperatePayload, market: Option<models::LendBorrowMarket>) -> Result<models::LendBorrowOperateTransactionResponse, Error<lend_borrow_api::BuildBorrowOperateTransactionError>> {
        lend_borrow_api::build_borrow_operate_transaction(&self.config, lend_borrow_operate_payload, market).await
    }

    /// Returns borrow positions (NFTs) for one or more wallet addresses.  Pass multiple wallets as a comma-separated list in the `users` query parameter. 
    #[allow(clippy::too_many_arguments)]
    pub async fn list_borrow_positions(&self, users: &str, market: Option<models::LendBorrowMarket>) -> Result<Vec<models::LendBorrowBorrowPosition>, Error<lend_borrow_api::ListBorrowPositionsError>> {
        lend_borrow_api::list_borrow_positions(&self.config, users, market).await
    }

    /// Returns all whitelisted borrow vaults for the requested market.
    #[allow(clippy::too_many_arguments)]
    pub async fn list_borrow_vaults(&self, market: Option<models::LendBorrowMarket>, rpc_url: Option<&str>) -> Result<Vec<models::LendBorrowBorrowVault>, Error<lend_borrow_api::ListBorrowVaultsError>> {
        lend_borrow_api::list_borrow_vaults(&self.config, market, rpc_url).await
    }
}

impl Portfolio {
    #[allow(clippy::too_many_arguments)]
    pub async fn portfolio_v1_platforms_get(&self) -> Result<Vec<models::PortfolioV1PlatformsGet200ResponseInner>, Error<portfolio_api::PortfolioV1PlatformsGetError>> {
        portfolio_api::portfolio_v1_platforms_get(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn portfolio_v1_positions_address_get(&self, address: &str, platforms: Option<&str>) -> Result<models::PortfolioV1PositionsAddressGet200Response, Error<portfolio_api::PortfolioV1PositionsAddressGetError>> {
        portfolio_api::portfolio_v1_positions_address_get(&self.config, address, platforms).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn portfolio_v1_staked_jup_address_get(&self, address: &str) -> Result<models::PortfolioV1StakedJupAddressGet200Response, Error<portfolio_api::PortfolioV1StakedJupAddressGetError>> {
        portfolio_api::portfolio_v1_staked_jup_address_get(&self.config, address).await
    }
}

impl Prediction {
    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_event_id_get(&self, event_id: &str, include_markets: Option<bool>, include_all_markets: Option<bool>) -> Result<models::PredictionEvent, Error<prediction_api::PredictionV1EventsEventIdGetError>> {
        prediction_api::prediction_v1_events_event_id_get(&self.config, event_id, include_markets, include_all_markets).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_event_id_markets_get(&self, event_id: &str, start: Option<i32>, end: Option<i32>) -> Result<models::PredictionV1EventsEventIdMarketsGet200Response, Error<prediction_api::PredictionV1EventsEventIdMarketsGetError>> {
        prediction_api::prediction_v1_events_event_id_markets_get(&self.config, event_id, start, end).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_event_id_markets_market_id_get(&self, event_id: &str, market_id: &str) -> Result<models::PredictionMarket, Error<prediction_api::PredictionV1EventsEventIdMarketsMarketIdGetError>> {
        prediction_api::prediction_v1_events_event_id_markets_market_id_get(&self.config, event_id, market_id).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_event_id_score_get(&self, event_id: &str) -> Result<models::PredictionGameScore, Error<prediction_api::PredictionV1EventsEventIdScoreGetError>> {
        prediction_api::prediction_v1_events_event_id_score_get(&self.config, event_id).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_get(&self, provider: Option<&str>, include_markets: Option<bool>, include_all_markets: Option<bool>, start: Option<i32>, end: Option<i32>, category: Option<&str>, subcategory: Option<models::PredictionV1EventsGetSubcategoryParameter>, sort_by: Option<&str>, sort_direction: Option<&str>, filter: Option<&str>, tags: Option<&str>) -> Result<models::PredictionV1EventsGet200Response, Error<prediction_api::PredictionV1EventsGetError>> {
        prediction_api::prediction_v1_events_get(&self.config, provider, include_markets, include_all_markets, start, end, category, subcategory, sort_by, sort_direction, filter, tags).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_scores_get(&self, event_ids: &str) -> Result<models::PredictionV1EventsScoresGet200Response, Error<prediction_api::PredictionV1EventsScoresGetError>> {
        prediction_api::prediction_v1_events_scores_get(&self.config, event_ids).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_search_get(&self, query: &str, provider: Option<&str>, limit: Option<i32>) -> Result<models::PredictionV1EventsSearchGet200Response, Error<prediction_api::PredictionV1EventsSearchGetError>> {
        prediction_api::prediction_v1_events_search_get(&self.config, query, provider, limit).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_events_suggested_pubkey_get(&self, pubkey: &str, provider: Option<&str>) -> Result<models::PredictionV1EventsSuggestedPubkeyGet200Response, Error<prediction_api::PredictionV1EventsSuggestedPubkeyGetError>> {
        prediction_api::prediction_v1_events_suggested_pubkey_get(&self.config, pubkey, provider).await
    }

    /// Submit a signed order transaction for execution. Pass the base64 `signedTransaction` together with the `execution.context` object returned by the order build (`POST /orders`, or `DELETE /positions/{positionPubkey}` for a sell), unchanged. Jupiter Forecast (bisonfi) orders execute as an atomic swap through this endpoint and the transaction signature is returned on success.
    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_execute_post(&self, prediction_execute_request: models::PredictionExecuteRequest) -> Result<models::PredictionExecuteResponse, Error<prediction_api::PredictionV1ExecutePostError>> {
        prediction_api::prediction_v1_execute_post(&self.config, prediction_execute_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_forecast_get(&self, market_id: &str) -> Result<models::PredictionV1ForecastGet200Response, Error<prediction_api::PredictionV1ForecastGetError>> {
        prediction_api::prediction_v1_forecast_get(&self.config, market_id).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_history_get(&self, start: Option<i32>, end: Option<i32>, owner_pubkey: Option<&str>, id: Option<i32>, position_pubkey: Option<&str>) -> Result<models::PredictionV1HistoryGet200Response, Error<prediction_api::PredictionV1HistoryGetError>> {
        prediction_api::prediction_v1_history_get(&self.config, start, end, owner_pubkey, id, position_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_leaderboards_get(&self, period: Option<&str>, limit: Option<i32>, metric: Option<&str>) -> Result<models::PredictionV1LeaderboardsGet200Response, Error<prediction_api::PredictionV1LeaderboardsGetError>> {
        prediction_api::prediction_v1_leaderboards_get(&self.config, period, limit, metric).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_markets_market_id_get(&self, market_id: &str) -> Result<models::PredictionMarket, Error<prediction_api::PredictionV1MarketsMarketIdGetError>> {
        prediction_api::prediction_v1_markets_market_id_get(&self.config, market_id).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_orderbook_market_id_get(&self, market_id: &str) -> Result<models::PredictionV1OrderbookMarketIdGet200Response, Error<prediction_api::PredictionV1OrderbookMarketIdGetError>> {
        prediction_api::prediction_v1_orderbook_market_id_get(&self.config, market_id).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_orders_get(&self, start: Option<i32>, end: Option<i32>, owner_pubkey: Option<&str>) -> Result<models::PredictionV1OrdersGet200Response, Error<prediction_api::PredictionV1OrdersGetError>> {
        prediction_api::prediction_v1_orders_get(&self.config, start, end, owner_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_orders_order_pubkey_get(&self, order_pubkey: &str) -> Result<models::PredictionOrder, Error<prediction_api::PredictionV1OrdersOrderPubkeyGetError>> {
        prediction_api::prediction_v1_orders_order_pubkey_get(&self.config, order_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_orders_post(&self, prediction_create_order_request: models::PredictionCreateOrderRequest) -> Result<models::PredictionCreateOrderResponse, Error<prediction_api::PredictionV1OrdersPostError>> {
        prediction_api::prediction_v1_orders_post(&self.config, prediction_create_order_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_orders_status_order_pubkey_get(&self, order_pubkey: &str) -> Result<models::PredictionV1OrdersStatusOrderPubkeyGet200Response, Error<prediction_api::PredictionV1OrdersStatusOrderPubkeyGetError>> {
        prediction_api::prediction_v1_orders_status_order_pubkey_get(&self.config, order_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_positions_delete(&self, prediction_close_all_positions_request: models::PredictionCloseAllPositionsRequest) -> Result<models::PredictionV1PositionsDelete200Response, Error<prediction_api::PredictionV1PositionsDeleteError>> {
        prediction_api::prediction_v1_positions_delete(&self.config, prediction_close_all_positions_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_positions_get(&self, start: Option<i32>, end: Option<i32>, owner_pubkey: Option<&str>, market_pubkey: Option<&str>, market_id: Option<&str>, is_yes: Option<&str>) -> Result<models::PredictionV1PositionsGet200Response, Error<prediction_api::PredictionV1PositionsGetError>> {
        prediction_api::prediction_v1_positions_get(&self.config, start, end, owner_pubkey, market_pubkey, market_id, is_yes).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_positions_position_pubkey_claim_post(&self, position_pubkey: &str, prediction_claim_position_request: models::PredictionClaimPositionRequest) -> Result<models::PredictionClaimPositionResponse, Error<prediction_api::PredictionV1PositionsPositionPubkeyClaimPostError>> {
        prediction_api::prediction_v1_positions_position_pubkey_claim_post(&self.config, position_pubkey, prediction_claim_position_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_positions_position_pubkey_delete(&self, position_pubkey: &str, prediction_close_position_request: models::PredictionClosePositionRequest) -> Result<models::PredictionCreateOrderResponse, Error<prediction_api::PredictionV1PositionsPositionPubkeyDeleteError>> {
        prediction_api::prediction_v1_positions_position_pubkey_delete(&self.config, position_pubkey, prediction_close_position_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_positions_position_pubkey_get(&self, position_pubkey: &str) -> Result<models::PredictionPosition, Error<prediction_api::PredictionV1PositionsPositionPubkeyGetError>> {
        prediction_api::prediction_v1_positions_position_pubkey_get(&self.config, position_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_profiles_owner_pubkey_get(&self, owner_pubkey: &str) -> Result<models::PredictionV1ProfilesOwnerPubkeyGet200Response, Error<prediction_api::PredictionV1ProfilesOwnerPubkeyGetError>> {
        prediction_api::prediction_v1_profiles_owner_pubkey_get(&self.config, owner_pubkey).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_profiles_owner_pubkey_pnl_history_get(&self, owner_pubkey: &str, interval: Option<&str>, count: Option<i32>) -> Result<models::PredictionV1ProfilesOwnerPubkeyPnlHistoryGet200Response, Error<prediction_api::PredictionV1ProfilesOwnerPubkeyPnlHistoryGetError>> {
        prediction_api::prediction_v1_profiles_owner_pubkey_pnl_history_get(&self.config, owner_pubkey, interval, count).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_trades_get(&self) -> Result<models::PredictionV1TradesGet200Response, Error<prediction_api::PredictionV1TradesGetError>> {
        prediction_api::prediction_v1_trades_get(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_trading_status_get(&self) -> Result<models::PredictionTradingStatusResponse, Error<prediction_api::PredictionV1TradingStatusGetError>> {
        prediction_api::prediction_v1_trading_status_get(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn prediction_v1_vault_info_get(&self) -> Result<models::PredictionV1VaultInfoGet200Response, Error<prediction_api::PredictionV1VaultInfoGetError>> {
        prediction_api::prediction_v1_vault_info_get(&self.config).await
    }
}

impl PriceV2 {
    #[allow(clippy::too_many_arguments)]
    pub async fn price_v2_get(&self, ids: &str, vs_token: Option<&str>, show_extra_info: Option<&str>) -> Result<models::PriceV2PriceResponse, Error<price_v2_api::PriceV2GetError>> {
        price_v2_api::price_v2_get(&self.config, ids, vs_token, show_extra_info).await
    }
}

impl PriceV3 {
    /// Get USD prices for up to 50 tokens per request. Tokens without a reliable price are omitted from the response. 
    #[allow(clippy::too_many_arguments)]
    pub async fn price_v3_get(&self, ids: &str) -> Result<std::collections::HashMap<String, models::PriceV3Get200ResponseValue>, Error<price_v3_api::PriceV3GetError>> {
        price_v3_api::price_v3_get(&self.config, ids).await
    }
}

impl Recurring {
    /// Request for a base64-encoded unsigned recurring order cancellation transaction to be used in `POST /recurring/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn cancel_order(&self, recurring_close_recurring: models::RecurringCloseRecurring) -> Result<models::RecurringRecurringResponse, Error<recurring_api::CancelOrderError>> {
        recurring_api::cancel_order(&self.config, recurring_close_recurring).await
    }

    /// Request for a base64-encoded unsigned recurring order creation transaction to be used in `POST /recurring/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn create_order(&self, recurring_create_recurring: models::RecurringCreateRecurring) -> Result<models::RecurringRecurringResponse, Error<recurring_api::CreateOrderError>> {
        recurring_api::create_order(&self.config, recurring_create_recurring).await
    }

    /// Execute the signed transaction and get the execution status 
    #[allow(clippy::too_many_arguments)]
    pub async fn execute(&self, recurring_execute_recurring: models::RecurringExecuteRecurring) -> Result<models::RecurringExecuteRecurringResponse, Error<recurring_api::ExecuteError>> {
        recurring_api::execute(&self.config, recurring_execute_recurring).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn price_deposit(&self, recurring_deposit_price_recurring: models::RecurringDepositPriceRecurring) -> Result<models::RecurringRecurringResponse, Error<recurring_api::PriceDepositError>> {
        recurring_api::price_deposit(&self.config, recurring_deposit_price_recurring).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn price_withdraw(&self, recurring_withdraw_price_recurring: models::RecurringWithdrawPriceRecurring) -> Result<models::RecurringRecurringResponse, Error<recurring_api::PriceWithdrawError>> {
        recurring_api::price_withdraw(&self.config, recurring_withdraw_price_recurring).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn recurring_v1_get_recurring_orders_get(&self, recurring_type: models::RecurringRecurringOrderType, order_status: models::RecurringOrderState, user: &str, page: Option<i64>, mint: Option<&str>, include_failed_tx: bool) -> Result<models::RecurringGetRecurringOrderResponse, Error<recurring_api::RecurringV1GetRecurringOrdersGetError>> {
        recurring_api::recurring_v1_get_recurring_orders_get(&self.config, recurring_type, order_status, user, page, mint, include_failed_tx).await
    }
}

impl SendApi {
    /// Request for a base64-encoded unsigned Send transaction 
    #[allow(clippy::too_many_arguments)]
    pub async fn send_v1_craft_clawback_post(&self, send_v1_craft_clawback_post_request: models::SendV1CraftClawbackPostRequest) -> Result<models::SendV1CraftClawbackPost200Response, Error<send_api::SendV1CraftClawbackPostError>> {
        send_api::send_v1_craft_clawback_post(&self.config, send_v1_craft_clawback_post_request).await
    }

    /// Request for a base64-encoded unsigned Send transaction 
    #[allow(clippy::too_many_arguments)]
    pub async fn send_v1_craft_send_post(&self, send_v1_craft_send_post_request: models::SendV1CraftSendPostRequest) -> Result<models::SendV1CraftSendPost200Response, Error<send_api::SendV1CraftSendPostError>> {
        send_api::send_v1_craft_send_post(&self.config, send_v1_craft_send_post_request).await
    }

    /// Request for the invite history of an address 
    #[allow(clippy::too_many_arguments)]
    pub async fn send_v1_invite_history_get(&self, address: &str, page: Option<i32>) -> Result<models::SendInviteDataResponse, Error<send_api::SendV1InviteHistoryGetError>> {
        send_api::send_v1_invite_history_get(&self.config, address, page).await
    }

    /// Request for the pending invites of an address 
    #[allow(clippy::too_many_arguments)]
    pub async fn send_v1_pending_invites_get(&self, address: &str, page: Option<i32>) -> Result<models::SendInviteDataResponse, Error<send_api::SendV1PendingInvitesGetError>> {
        send_api::send_v1_pending_invites_get(&self.config, address, page).await
    }
}

impl Studio {
    /// Request for a base64-encoded unsigned transaction to claim creator trading fees of a Dynamic Bonding Curve pool - Handles both direct creator ownership and proxy-based ownership. 
    #[allow(clippy::too_many_arguments)]
    pub async fn studio_v1_dbc_fee_create_tx_post(&self, studio_create_claim_fee_dbc_transaction_request_body: Option<models::StudioCreateClaimFeeDbcTransactionRequestBody>) -> Result<models::StudioV1DbcFeeCreateTxPost200Response, Error<studio_api::StudioV1DbcFeeCreateTxPostError>> {
        studio_api::studio_v1_dbc_fee_create_tx_post(&self.config, studio_create_claim_fee_dbc_transaction_request_body).await
    }

    /// Request for unclaimed creator trading fees of a Dynamic Bonding Curve pool 
    #[allow(clippy::too_many_arguments)]
    pub async fn studio_v1_dbc_fee_post(&self, studio_v1_dbc_fee_post_request: Option<models::StudioV1DbcFeePostRequest>) -> Result<models::StudioV1DbcFeePost200Response, Error<studio_api::StudioV1DbcFeePostError>> {
        studio_api::studio_v1_dbc_fee_post(&self.config, studio_v1_dbc_fee_post_request).await
    }

    /// Request for pool addresses for a given token mint 
    #[allow(clippy::too_many_arguments)]
    pub async fn studio_v1_dbc_pool_addresses_mint_get(&self, mint: &str) -> Result<models::StudioV1DbcPoolAddressesMintGet200Response, Error<studio_api::StudioV1DbcPoolAddressesMintGetError>> {
        studio_api::studio_v1_dbc_pool_addresses_mint_get(&self.config, mint).await
    }

    /// Request for a base64-encoded unsigned transaction to create a Dynamic Bonding Curve pool with token metadata 
    #[allow(clippy::too_many_arguments)]
    pub async fn studio_v1_dbc_pool_create_tx_post(&self, studio_create_dbc_transaction_request_body: Option<models::StudioCreateDbcTransactionRequestBody>) -> Result<models::StudioCreateDbcTransactionResponse, Error<studio_api::StudioV1DbcPoolCreateTxPostError>> {
        studio_api::studio_v1_dbc_pool_create_tx_post(&self.config, studio_create_dbc_transaction_request_body).await
    }

    /// Execute the signed transaction, and optionally upload content and header image 
    #[allow(clippy::too_many_arguments)]
    pub async fn studio_v1_dbc_pool_submit_post(&self, transaction: &str, owner: &str, content: Option<&str>, header_image: Option<std::path::PathBuf>) -> Result<models::StudioV1DbcPoolSubmitPost200Response, Error<studio_api::StudioV1DbcPoolSubmitPostError>> {
        studio_api::studio_v1_dbc_pool_submit_post(&self.config, transaction, owner, content, header_image).await
    }
}

impl SwapV1 {
    /// Returns a hash, which key is the program id and value is the label. This is used to help map error from transaction by identifying the fault program id. This can be used in conjunction with the `excludeDexes` or `dexes` parameter. 
    #[allow(clippy::too_many_arguments)]
    pub async fn program_id_to_label_get(&self) -> Result<std::collections::HashMap<String, String>, Error<swap_v1_api::ProgramIdToLabelGetError>> {
        swap_v1_api::program_id_to_label_get(&self.config).await
    }

    /// Request for a quote to be used in `POST /swap` 
    #[allow(clippy::too_many_arguments)]
    pub async fn quote_get(&self, input_mint: &str, output_mint: &str, amount: i32, slippage_bps: Option<i32>, swap_mode: Option<&str>, dexes: Option<Vec<String>>, exclude_dexes: Option<Vec<String>>, restrict_intermediate_tokens: Option<bool>, only_direct_routes: Option<bool>, as_legacy_transaction: Option<bool>, platform_fee_bps: Option<i32>, max_accounts: Option<i32>, instruction_version: Option<&str>, dynamic_slippage: Option<bool>, for_jito_bundle: Option<bool>) -> Result<models::SwapV1QuoteResponse, Error<swap_v1_api::QuoteGetError>> {
        swap_v1_api::quote_get(&self.config, input_mint, output_mint, amount, slippage_bps, swap_mode, dexes, exclude_dexes, restrict_intermediate_tokens, only_direct_routes, as_legacy_transaction, platform_fee_bps, max_accounts, instruction_version, dynamic_slippage, for_jito_bundle).await
    }

    /// Request for swap instructions that you can use from the quote you get from `/quote` 
    #[allow(clippy::too_many_arguments)]
    pub async fn swap_instructions_post(&self, swap_v1_swap_request: models::SwapV1SwapRequest) -> Result<models::SwapV1SwapInstructionsResponse, Error<swap_v1_api::SwapInstructionsPostError>> {
        swap_v1_api::swap_instructions_post(&self.config, swap_v1_swap_request).await
    }

    /// Request for a base64-encoded unsigned swap transaction based on the `/quote` response 
    #[allow(clippy::too_many_arguments)]
    pub async fn swap_post(&self, swap_v1_swap_request: models::SwapV1SwapRequest) -> Result<models::SwapV1SwapResponse, Error<swap_v1_api::SwapPostError>> {
        swap_v1_api::swap_post(&self.config, swap_v1_swap_request).await
    }
}

impl SwapV2 {
    /// Get a swap quote with raw instructions for building custom transactions. This is the advanced path for integrators who need full transaction control (add custom instructions, CPI, custom payer).  You are responsible for assembling the transaction, signing, and sending via your own RPC. The `/execute` endpoint is not available for `/build` transactions.  Routing is Metis only. No swap fees are charged by Jupiter. 
    #[allow(clippy::too_many_arguments)]
    pub async fn get_build(&self, input_mint: &str, output_mint: &str, amount: &str, taker: &str, slippage_bps: Option<models::GetBuildSlippageBpsParameter>, mode: Option<&str>, dexes: Option<&str>, exclude_dexes: Option<&str>, platform_fee_bps: Option<i32>, fee_account: Option<&str>, max_accounts: Option<i32>, payer: Option<&str>, wrap_and_unwrap_sol: Option<bool>, destination_token_account: Option<&str>, native_destination_account: Option<&str>, blockhash_slots_to_expiry: Option<i32>, tip_amount: Option<&str>, compute_unit_price_percentile: Option<models::GetBuildComputeUnitPricePercentileParameter>, for_jito_bundle: Option<bool>) -> Result<models::GetBuild200Response, Error<swap_v2_api::GetBuildError>> {
        swap_v2_api::get_build(&self.config, input_mint, output_mint, amount, taker, slippage_bps, mode, dexes, exclude_dexes, platform_fee_bps, fee_account, max_accounts, payer, wrap_and_unwrap_sol, destination_token_account, native_destination_account, blockhash_slots_to_expiry, tip_amount, compute_unit_price_percentile, for_jito_bundle).await
    }

    /// Get a swap quote and assembled transaction. This is the default happy path with all Ultra benefits (predictive execution, RTSE, Jupiter Beam, gasless, multi-router competition).  Without optional parameters, all routers compete for the best price (Metis, JupiterZ RFQ, Dflow, OKX). Setting `payer` to a wallet different from `taker` restricts routing to Metis. 
    #[allow(clippy::too_many_arguments)]
    pub async fn get_order(&self, input_mint: &str, output_mint: &str, amount: &str, taker: Option<&str>, receiver: Option<&str>, swap_mode: Option<&str>, slippage_bps: Option<i32>, referral_account: Option<&str>, referral_fee: Option<f64>, payer: Option<&str>, priority_fee_lamports: Option<f64>, jito_tip_lamports: Option<f64>, broadcast_fee_type: Option<&str>, exclude_routers: Option<&str>, exclude_dexes: Option<&str>) -> Result<models::GetOrder200Response, Error<swap_v2_api::GetOrderError>> {
        swap_v2_api::get_order(&self.config, input_mint, output_mint, amount, taker, receiver, swap_mode, slippage_bps, referral_account, referral_fee, payer, priority_fee_lamports, jito_tip_lamports, broadcast_fee_type, exclude_routers, exclude_dexes).await
    }

    /// Execute a signed transaction from `/order`. Handles transaction landing, confirmation, and retry.  Only available for transactions obtained via `/order`. Transactions built via `/build` must be sent through your own RPC. 
    #[allow(clippy::too_many_arguments)]
    pub async fn post_execute(&self, post_execute_request: models::PostExecuteRequest) -> Result<models::PostExecute200Response, Error<swap_v2_api::PostExecuteError>> {
        swap_v2_api::post_execute(&self.config, post_execute_request).await
    }
}

impl TokensV1 {
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_all_get(&self) -> Result<Vec<models::TokensV1Mint>, Error<tokens_v1_api::TokensV1AllGetError>> {
        tokens_v1_api::tokens_v1_all_get(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_market_market_address_mints_get(&self, market_address: &str) -> Result<Vec<String>, Error<tokens_v1_api::TokensV1MarketMarketAddressMintsGetError>> {
        tokens_v1_api::tokens_v1_market_market_address_mints_get(&self.config, market_address).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_mints_tradable_get(&self) -> Result<Vec<String>, Error<tokens_v1_api::TokensV1MintsTradableGetError>> {
        tokens_v1_api::tokens_v1_mints_tradable_get(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_new_get(&self, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<models::TokensV1MintWithCreationTimeAndMarkets>, Error<tokens_v1_api::TokensV1NewGetError>> {
        tokens_v1_api::tokens_v1_new_get(&self.config, limit, offset).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_tagged_tag_get(&self, tag: &str) -> Result<models::TokensV1MintIncludingDuplicates, Error<tokens_v1_api::TokensV1TaggedTagGetError>> {
        tokens_v1_api::tokens_v1_tagged_tag_get(&self.config, tag).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v1_token_mint_address_get(&self, mint_address: &str) -> Result<models::TokensV1MintIncludingDuplicates, Error<tokens_v1_api::TokensV1TokenMintAddressGetError>> {
        tokens_v1_api::tokens_v1_token_mint_address_get(&self.config, mint_address).await
    }
}

impl TokensV2 {
    /// Returns an array of mints and their information for the given category and interval 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_category_interval_get(&self, category: &str, interval: &str, limit: Option<i32>) -> Result<Vec<models::TokensV2MintInformation>, Error<tokens_v2_api::TokensV2CategoryIntervalGetError>> {
        tokens_v2_api::tokens_v2_category_interval_get(&self.config, category, interval, limit).await
    }

    /// Returns an array of mints that recently had their **first created pool** - Default to 30 mints in response 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_recent_get(&self) -> Result<Vec<models::TokensV2MintInformation>, Error<tokens_v2_api::TokensV2RecentGetError>> {
        tokens_v2_api::tokens_v2_recent_get(&self.config).await
    }

    /// Request a search by token's symbol, name or mint address 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_search_get(&self, query: &str) -> Result<Vec<models::TokensV2MintInformation>, Error<tokens_v2_api::TokensV2SearchGetError>> {
        tokens_v2_api::tokens_v2_search_get(&self.config, query).await
    }

    /// Request an array of mints and their information by a tag - Note that this will return the entire array of existing mints that belongs to the tag. 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_tag_get(&self, query: &str) -> Result<Vec<models::TokensV2MintInformation>, Error<tokens_v2_api::TokensV2TagGetError>> {
        tokens_v2_api::tokens_v2_tag_get(&self.config, query).await
    }
}

impl TokensV2Verification {
    /// Checks whether a token is eligible for express verification and metadata updates. If both `canVerify` and `canMetadata` are `false`, any submission will be rejected before payment is charged. 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_verify_express_check_eligibility_get(&self, token_id: &str) -> Result<models::TokensV2VerificationCheckEligibilityResponse, Error<tokens_v2_verification_api::TokensV2VerifyExpressCheckEligibilityGetError>> {
        tokens_v2_verification_api::tokens_v2_verify_express_check_eligibility_get(&self.config, token_id).await
    }

    /// Returns an unsigned Solana transaction worth 1000 JUP as payment for express verification. JUP transfers directly; SOL, USDC, and JUPUSD craft an Ultra swap to 1000 JUP. The `requestId` in the response is required for the execute step. 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_verify_express_craft_txn_get(&self, sender_address: &str, payment_currency: Option<models::TokensV2VerificationPaymentCurrency>) -> Result<models::TokensV2VerificationCraftTxnResponse, Error<tokens_v2_verification_api::TokensV2VerifyExpressCraftTxnGetError>> {
        tokens_v2_verification_api::tokens_v2_verify_express_craft_txn_get(&self.config, sender_address, payment_currency).await
    }

    /// Submits the signed payment transaction, records the payment, creates a verification request, and optionally submits token metadata updates. Verification and metadata updates are reviewed independently. 
    #[allow(clippy::too_many_arguments)]
    pub async fn tokens_v2_verify_express_execute_post(&self, tokens_v2_verification_express_execute_body: models::TokensV2VerificationExpressExecuteBody) -> Result<models::TokensV2VerificationExpressExecuteResponse, Error<tokens_v2_verification_api::TokensV2VerifyExpressExecutePostError>> {
        tokens_v2_verification_api::tokens_v2_verify_express_execute_post(&self.config, tokens_v2_verification_express_execute_body).await
    }
}

impl Transaction {
    /// `tx.jup.ag` is a Solana RPC-compatible endpoint (compatible where possible) that forwards signed transactions to the Solana cluster through Jupiter's landing infrastructure. It implements the standard Solana [`sendTransaction`](https://solana.com/docs/rpc/http/sendtransaction) method, so any Solana client can point at it. A success response means the transaction was accepted and forwarded, not that it landed; confirm landing on your own RPC.  It is send-only: `getLatestBlockhash`, `simulateTransaction`, and confirmation queries are not served. Keep your own RPC for those.  **Authentication:** requires your Jupiter API key in the `x-api-key` header.  **Validation:** - Transaction must be a valid signed Solana transaction with all required signatures - Transaction must contain a SOL transfer of >= 1,000,000 lamports (0.001 SOL) to one of the 16 tip receiver accounts - Transaction must not exceed the Solana transaction size limit  **Tip receiver accounts (16 Jupiter V6 program authorities):**  `GGztQqQ6pCPaJQnNpXBgELr5cs3WwDakRbh1iEMzjgSJ`, `2MFoS3MPtvyQ4Wh4M9pdfPjz6UhVoNbFbGJAskCPCj3h`, `BQ72nSv9f3PRyRKCBnHLVrerrv37CYTHm5h3s9VSGQDV`, `6U91aKa8pmMxkJwBCfPTmUEfZi6dHe7DcFq2ALvB2tbB`, `4xDsmeTWPNjgSVSS1VTfzFq3iHZhp77ffPkAmkZkdu71`, `CapuXNQoDviLvU1PxFiizLgPNQCxrsag1uMeyk6zLVps`, `9nnLbotNTcUhvbrsA6Mdkx45Sm82G35zo28AqUvjExn8`, `6LXutJvKUw8Q5ue2gCgKHQdAN4suWW8awzFVC6XCguFx`, `HFqp6ErWHY6Uzhj8rFyjYuDya2mXUpYEk8VW75K9PSiY`, `DSN3j1ykL3obAVNv7ZX49VsFCPe4LqzxHnmtLiPwY6xg`, `69yhtoJR4JYPPABZcSNkzuqbaFbwHsCkja1sP1Q2aVT5`, `HU23r7UoZbqTUuh3vA7emAGztFtqwTeVips789vqxxBw`, `3LoAYHuSd7Gh8d7RTFnhvYtiTiefdZ5ByamU42vkzd76`, `3CgvbiM3op4vjrrjH2zcrQUwsqh5veNVRjFCB9N6sRoD`, `GP8StUXNYSZjPikyRsvkTbvRV1GBxMErb59cpeCJnDf1`, `7iWnBRRhBCiNXXPhqiGzvvBkKrvFSWqqmxRyu9VyYBxE`  Randomise which account you send to across transactions to reduce write-lock contention. 
    #[allow(clippy::too_many_arguments)]
    pub async fn send_transaction(&self, send_transaction_request: Option<models::SendTransactionRequest>) -> Result<models::SendTransaction200Response, Error<transaction_api::SendTransactionError>> {
        transaction_api::send_transaction(&self.config, send_transaction_request).await
    }
}

impl TriggerV1 {
    /// Request for a base64-encoded unsigned trigger order cancellation transaction to be used in `POST /trigger/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v1_cancel_order_post(&self, trigger_v1_cancel_order_post_request: Option<models::TriggerV1CancelOrderPostRequest>) -> Result<models::TriggerV1CancelOrderPost200Response, Error<trigger_v1_api::TriggerV1CancelOrderPostError>> {
        trigger_v1_api::trigger_v1_cancel_order_post(&self.config, trigger_v1_cancel_order_post_request).await
    }

    /// Request for a base64-encoded unsigned trigger order cancellation transaction(s) to be used in `POST /trigger/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v1_cancel_orders_post(&self, cancel_orders_request_body: Option<models::CancelOrdersRequestBody>) -> Result<models::TriggerV1CancelOrdersPost200Response, Error<trigger_v1_api::TriggerV1CancelOrdersPostError>> {
        trigger_v1_api::trigger_v1_cancel_orders_post(&self.config, cancel_orders_request_body).await
    }

    /// Request for a base64-encoded unsigned trigger order creation transaction to be used in `POST /trigger/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v1_create_order_post(&self, create_orders_request_body: Option<models::CreateOrdersRequestBody>) -> Result<models::TriggerV1CreateOrderPost200Response, Error<trigger_v1_api::TriggerV1CreateOrderPostError>> {
        trigger_v1_api::trigger_v1_create_order_post(&self.config, create_orders_request_body).await
    }

    /// Execute the signed transaction and get the execution status 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v1_execute_post(&self, execute_request_body: models::ExecuteRequestBody) -> Result<models::TriggerV1ExecutePost200Response, Error<trigger_v1_api::TriggerV1ExecutePostError>> {
        trigger_v1_api::trigger_v1_execute_post(&self.config, execute_request_body).await
    }

    /// Request for the active or historical orders associated to the provided account 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v1_get_trigger_orders_get(&self, user: &str, order_status: &str, page: Option<&str>, include_failed_tx: Option<&str>, input_mint: Option<&str>, output_mint: Option<&str>) -> Result<models::TriggerV1GetTriggerOrdersGet200Response, Error<trigger_v1_api::TriggerV1GetTriggerOrdersGetError>> {
        trigger_v1_api::trigger_v1_get_trigger_orders_get(&self.config, user, order_status, page, include_failed_tx, input_mint, output_mint).await
    }
}

impl TriggerV2 {
    /// Request a challenge to sign with your wallet. Use `message` for standard wallets or `transaction` for hardware wallets that only support transaction signing. Challenges expire after 5 minutes. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_auth_challenge_post(&self, trigger_v2_auth_challenge_post_request: models::TriggerV2AuthChallengePostRequest) -> Result<models::TriggerV2AuthChallengePost200Response, Error<trigger_v2_api::TriggerV2AuthChallengePostError>> {
        trigger_v2_api::trigger_v2_auth_challenge_post(&self.config, trigger_v2_auth_challenge_post_request).await
    }

    /// Submit the signed challenge to receive a JWT token valid for 24 hours. Include the JWT in all subsequent authenticated requests via the `Authorization: Bearer` header. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_auth_verify_post(&self, trigger_v2_auth_verify_post_request: models::TriggerV2AuthVerifyPostRequest) -> Result<models::TriggerV2AuthVerifyPost200Response, Error<trigger_v2_api::TriggerV2AuthVerifyPostError>> {
        trigger_v2_api::trigger_v2_auth_verify_post(&self.config, trigger_v2_auth_verify_post_request).await
    }

    /// Build an unsigned transaction to deposit tokens from your wallet into your vault. The vault address is automatically resolved from your JWT token. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_deposit_craft_post(&self, trigger_v2_deposit_craft_post_request: models::TriggerV2DepositCraftPostRequest) -> Result<models::TriggerV2DepositCraftPost200Response, Error<trigger_v2_api::TriggerV2DepositCraftPostError>> {
        trigger_v2_api::trigger_v2_deposit_craft_post(&self.config, trigger_v2_deposit_craft_post_request).await
    }

    /// Step 1 of the two-step cancellation. Moves the order to `withdrawing` and returns an unsigned withdrawal transaction for the unfilled remainder. Already-filled rounds are not reversed. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_dca_cancel_id_post(&self, id: &str) -> Result<models::TriggerV2OrdersDcaCancelIdPost200Response, Error<trigger_v2_api::TriggerV2OrdersDcaCancelIdPostError>> {
        trigger_v2_api::trigger_v2_orders_dca_cancel_id_post(&self.config, id).await
    }

    /// Step 2 of the two-step cancellation. Submit the signed withdrawal transaction to return the remaining funds and move the order to `cancelled`. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_dca_confirm_cancel_id_post(&self, id: &str, trigger_v2_orders_dca_confirm_cancel_id_post_request: models::TriggerV2OrdersDcaConfirmCancelIdPostRequest) -> Result<models::TriggerV2TxSignatureResponse, Error<trigger_v2_api::TriggerV2OrdersDcaConfirmCancelIdPostError>> {
        trigger_v2_api::trigger_v2_orders_dca_confirm_cancel_id_post(&self.config, id, trigger_v2_orders_dca_confirm_cancel_id_post_request).await
    }

    /// Create a dollar-cost averaging order that splits a single deposit into `orderCount` equal rounds executed every `intervalSeconds`. Submit the signed deposit transaction from `/deposit/craft` (crafted with `orderType: \"dca\"`).  Call this path with no trailing slash. `POST /orders/dca/` returns 404.  Rounds execute as Jupiter swaps with Ultra-managed (RTSE) slippage; there is no slippage parameter. Each round pays the standard Jupiter swap fee (no separate DCA fee), and the output settles directly to the taker's wallet. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_dca_post(&self, trigger_v2_orders_dca_post_request: models::TriggerV2OrdersDcaPostRequest) -> Result<models::TriggerV2TxSignatureResponse, Error<trigger_v2_api::TriggerV2OrdersDcaPostError>> {
        trigger_v2_api::trigger_v2_orders_dca_post(&self.config, trigger_v2_orders_dca_post_request).await
    }

    /// List the authenticated wallet's DCA orders with full event history.
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_history_dca_get(&self, state: Option<&str>, mint: Option<&str>, limit: Option<f64>, offset: Option<f64>, sort: Option<&str>, dir: Option<&str>) -> Result<models::TriggerV2OrdersHistoryDcaGet200Response, Error<trigger_v2_api::TriggerV2OrdersHistoryDcaGetError>> {
        trigger_v2_api::trigger_v2_orders_history_dca_get(&self.config, state, mint, limit, offset, sort, dir).await
    }

    /// Get a single DCA order by ID, including fill history and events. The path requires the `dca` segment. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_history_dca_id_get(&self, id: &str) -> Result<models::TriggerV2DcaHistoryItem, Error<trigger_v2_api::TriggerV2OrdersHistoryDcaIdGetError>> {
        trigger_v2_api::trigger_v2_orders_history_dca_id_get(&self.config, id).await
    }

    /// Retrieve paginated order history for the authenticated wallet. Filter by state, mint, and sort order. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_history_get(&self, state: Option<&str>, mint: Option<&str>, limit: Option<f64>, offset: Option<f64>, sort: Option<&str>, dir: Option<&str>) -> Result<models::TriggerV2OrdersHistoryGet200Response, Error<trigger_v2_api::TriggerV2OrdersHistoryGetError>> {
        trigger_v2_api::trigger_v2_orders_history_get(&self.config, state, mint, limit, offset, sort, dir).await
    }

    /// Step 1 of the two-step cancellation flow. Returns a withdrawal transaction that must be signed and submitted via the confirm-cancel endpoint. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_price_cancel_order_id_post(&self, order_id: &str) -> Result<models::TriggerV2OrdersPriceCancelOrderIdPost200Response, Error<trigger_v2_api::TriggerV2OrdersPriceCancelOrderIdPostError>> {
        trigger_v2_api::trigger_v2_orders_price_cancel_order_id_post(&self.config, order_id).await
    }

    /// Step 2 of the two-step cancellation flow. Submit the signed withdrawal transaction to complete the cancellation and return funds to your wallet. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_price_confirm_cancel_order_id_post(&self, order_id: &str, trigger_v2_orders_price_confirm_cancel_order_id_post_request: models::TriggerV2OrdersPriceConfirmCancelOrderIdPostRequest) -> Result<models::TriggerV2TxSignatureResponse, Error<trigger_v2_api::TriggerV2OrdersPriceConfirmCancelOrderIdPostError>> {
        trigger_v2_api::trigger_v2_orders_price_confirm_cancel_order_id_post(&self.config, order_id, trigger_v2_orders_price_confirm_cancel_order_id_post_request).await
    }

    /// Update trigger price or slippage of an existing order.
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_price_order_id_patch(&self, order_id: &str, trigger_v2_orders_price_order_id_patch_request: models::TriggerV2OrdersPriceOrderIdPatchRequest) -> Result<models::TriggerV2OrdersPriceOrderIdPatch200Response, Error<trigger_v2_api::TriggerV2OrdersPriceOrderIdPatchError>> {
        trigger_v2_api::trigger_v2_orders_price_order_id_patch(&self.config, order_id, trigger_v2_orders_price_order_id_patch_request).await
    }

    /// Create a new price order. Supports three order types: - `single`: triggers when price crosses above/below threshold - `oco`: one-cancels-other (take-profit + stop-loss pair) - `otoco`: parent trigger activates a TP/SL pair on fill 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_orders_price_post(&self, trigger_v2_orders_price_post_request: models::TriggerV2OrdersPricePostRequest) -> Result<models::TriggerV2OrderResponse, Error<trigger_v2_api::TriggerV2OrdersPricePostError>> {
        trigger_v2_api::trigger_v2_orders_price_post(&self.config, trigger_v2_orders_price_post_request).await
    }

    /// Retrieve the vault associated with your authenticated wallet.
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_vault_get(&self) -> Result<models::TriggerV2VaultGet200Response, Error<trigger_v2_api::TriggerV2VaultGetError>> {
        trigger_v2_api::trigger_v2_vault_get(&self.config).await
    }

    /// Create a new Privy-managed vault wallet for your account. Call this once per wallet. Subsequent calls return the existing vault. 
    #[allow(clippy::too_many_arguments)]
    pub async fn trigger_v2_vault_register_get(&self) -> Result<models::TriggerV2VaultRegisterGet201Response, Error<trigger_v2_api::TriggerV2VaultRegisterGetError>> {
        trigger_v2_api::trigger_v2_vault_register_get(&self.config).await
    }
}

impl Ultra {
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_balances_address_get(&self, address: &str) -> Result<std::collections::HashMap<String, models::UltraV1BalancesAddressGet200ResponseValue>, Error<ultra_api::UltraV1BalancesAddressGetError>> {
        ultra_api::ultra_v1_balances_address_get(&self.config, address).await
    }

    /// Execute the signed transaction and get the execution status 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_execute_post(&self, ultra_v1_execute_post_request: Option<models::UltraV1ExecutePostRequest>) -> Result<models::UltraV1ExecutePost200Response, Error<ultra_api::UltraV1ExecutePostError>> {
        ultra_api::ultra_v1_execute_post(&self.config, ultra_v1_execute_post_request).await
    }

    /// Request for token balances of an account including token account information 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_holdings_address_get(&self, address: &str) -> Result<models::UltraHoldingsResponse, Error<ultra_api::UltraV1HoldingsAddressGetError>> {
        ultra_api::ultra_v1_holdings_address_get(&self.config, address).await
    }

    /// Request for native SOL holdings only, without other tokens 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_holdings_address_native_get(&self, address: &str) -> Result<models::UltraNativeHoldingsResponse, Error<ultra_api::UltraV1HoldingsAddressNativeGetError>> {
        ultra_api::ultra_v1_holdings_address_native_get(&self.config, address).await
    }

    /// Request for a base64-encoded unsigned swap transaction to be used in `POST /ultra/v1/execute` 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_order_get(&self, input_mint: &str, output_mint: &str, amount: &str, taker: Option<&str>, receiver: Option<&str>, payer: Option<&str>, close_authority: Option<&str>, referral_account: Option<&str>, referral_fee: Option<f64>, exclude_routers: Option<&str>, exclude_dexes: Option<&str>) -> Result<models::UltraV1OrderGet200Response, Error<ultra_api::UltraV1OrderGetError>> {
        ultra_api::ultra_v1_order_get(&self.config, input_mint, output_mint, amount, taker, receiver, payer, close_authority, referral_account, referral_fee, exclude_routers, exclude_dexes).await
    }

    /// Request for the list of routers available in the routing engine of Ultra, which is [Juno](/docs/routing#juno-liquidity-engine) 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_order_routers_get(&self) -> Result<Vec<models::UltraV1OrderRoutersGet200ResponseInner>, Error<ultra_api::UltraV1OrderRoutersGetError>> {
        ultra_api::ultra_v1_order_routers_get(&self.config).await
    }

    /// Request a search by token's symbol, name or mint address 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_search_get(&self, query: &str) -> Result<Vec<models::UltraMintInformation>, Error<ultra_api::UltraV1SearchGetError>> {
        ultra_api::ultra_v1_search_get(&self.config, query).await
    }

    /// Request for token information and warnings of mints 
    #[allow(clippy::too_many_arguments)]
    pub async fn ultra_v1_shield_get(&self, mints: &str) -> Result<models::UltraV1ShieldGet200Response, Error<ultra_api::UltraV1ShieldGetError>> {
        ultra_api::ultra_v1_shield_get(&self.config, mints).await
    }
}
