import { readdir } from "node:fs/promises";
import { basename, join, relative } from "node:path";

const APIS_DIRECTORY = join(import.meta.dir, "..", "generated/rust/src/apis");
const OUTPUT_PATH = join(import.meta.dir, "..", "clients/rust/src/generated_impls.rs");

const FUNCTION_PATTERN =
  /^pub async fn ([a-z0-9_]+)\(configuration: &configuration::Configuration,?\s*(.*)\) -> (.+) \{$/;

function toPascalCase(snake: string): string {
  return snake
    .split("_")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
    .join("");
}

function structNameForModule(moduleName: string): string {
  if (moduleName === "send_api") {
    return "SendApi";
  }

  return toPascalCase(moduleName.replace(/_api$/, ""));
}

function splitParams(params: string): string[] {
  const parts: string[] = [];
  let current = "";
  let depth = 0;

  for (const character of params) {
    if (character === "<" || character === "(") {
      depth += 1;
    } else if (character === ">" || character === ")") {
      depth -= 1;
    } else if (character === "," && depth === 0) {
      if (current.trim().length > 0) {
        parts.push(current.trim());
      }
      current = "";
      continue;
    }

    current += character;
  }

  if (current.trim().length > 0) {
    parts.push(current.trim());
  }

  return parts;
}

function parseParam(param: string): { name: string; type: string } {
  const separator = param.indexOf(":");

  if (separator === -1) {
    throw new TypeError(`Invalid generated parameter: ${param}`);
  }

  return {
    name: param.slice(0, separator).trim(),
    type: param.slice(separator + 1).trim(),
  };
}

function rewriteReturnType(returnType: string, moduleName: string): string {
  return returnType.replace(/Error<(\w+)>/g, `Error<${moduleName}::$1>`);
}

function precedingDocComments(lines: string[], functionLine: number): string[] {
  const docs: string[] = [];

  for (let index = functionLine - 1; index >= 0; index -= 1) {
    const line = lines[index];

    if (line === undefined || !line.startsWith("///")) {
      break;
    }

    docs.unshift(line);
  }

  return docs;
}

type GeneratedFunction = {
  docs: string[];
  name: string;
  params: Array<{ name: string; type: string }>;
  returnType: string;
};

function parseApiFile(source: string, fileName: string): GeneratedFunction[] {
  const lines = source.split(/\r?\n/);
  const functions: GeneratedFunction[] = [];

  for (const [index, line] of lines.entries()) {
    const match = line.match(FUNCTION_PATTERN);

    if (match === null || match[1] === undefined || match[3] === undefined) {
      continue;
    }

    functions.push({
      docs: precedingDocComments(lines, index),
      name: match[1],
      params: splitParams(match[2] ?? "").map(parseParam),
      returnType: match[3],
    });
  }

  if (functions.length === 0) {
    throw new TypeError(`No generated API functions found in ${fileName}`);
  }

  return functions;
}

function renderImpl(moduleName: string, functions: GeneratedFunction[]): string {
  const structName = structNameForModule(moduleName);
  const methods = functions.map((fn) => {
    const docs = fn.docs.map((line) => `    ${line}`).join("\n");
    const params = fn.params.map((param) => `, ${param.name}: ${param.type}`).join("");
    const args = ["&self.config", ...fn.params.map((param) => param.name)].join(", ");
    const returnType = rewriteReturnType(fn.returnType, moduleName);
    const header = docs.length > 0 ? `${docs}\n` : "";

    return `${header}    #[allow(clippy::too_many_arguments)]
    pub async fn ${fn.name}(&self${params}) -> ${returnType} {
        ${moduleName}::${fn.name}(${args}).await
    }`;
  });

  return `impl ${structName} {
${methods.join("\n\n")}
}`;
}

const apiFiles = (await readdir(APIS_DIRECTORY))
  .filter((fileName) => fileName.endsWith("_api.rs"))
  .sort((left, right) => left.localeCompare(right));

if (apiFiles.length === 0) {
  throw new TypeError(`No generated API modules found in ${APIS_DIRECTORY}`);
}

const modules: string[] = [];
const impls: string[] = [];

for (const fileName of apiFiles) {
  const moduleName = basename(fileName, ".rs");
  const source = await Bun.file(join(APIS_DIRECTORY, fileName)).text();
  modules.push(moduleName);
  impls.push(renderImpl(moduleName, parseApiFile(source, fileName)));
}

const output = `// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::client::*;
use jup_ag_api_generated::apis::{
    ${modules.join(",\n    ")},
};
use jup_ag_api_generated::apis::Error;
use jup_ag_api_generated::models;

${impls.join("\n\n")}
`;

await Bun.write(OUTPUT_PATH, output);

console.log(
  `Wrote ${relative(process.cwd(), OUTPUT_PATH)} from ${apiFiles.length} generated API modules.`,
);
